[package]
name = "engien"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-files = "0.6"
rand = "0.8"   
serde = { version = "1.0", features = ["derive"] } 
serde_json = "1.0" 
actix-cors = "0.6"